---
title: "Homeless death map"
author: "NearAndDistant"
date: "07/02/2022"
output: html_document
---

```{r}
library(tidyverse)

hld_tidy <- read_csv("https://raw.githubusercontent.com/NearAndDistant/ruk/main/data_scripts/ons_homeless_deaths/hdl_tidy.csv")

# filter
hld_flt <- hld_tidy %>% filter(year == 2020)

```

```{r}
# political boundaries
# boundary source: https://osdatahub.os.uk/downloads/open/BoundaryLine
library(sf)
library(rgdal)

# Counties and Unitary Authorities (Northamponshire, Buckinghamshire, Dorset)
lad <- 
  readOGR( 
  dsn     = here::here("projects/homelessness/raw_data/Local_Authority_Districts_(May_2021)_UK_BFE_V3"), 
  layer   = "LAD_MAY_2021_UK_BFE_V2",
  verbose = FALSE) 

# convert to sf
lad_sf <- 
  st_as_sf(lad) %>% 
  rmapshaper::ms_simplify() %>%
  janitor::clean_names() %>%
  select(area_code = "lad21cd", area_name = "lad21nm", long, lat, geometry)

```

```{r}

# joining for LAD
hld_lad <-
  hld_flt %>%
  left_join(lad_sf, by = "area_code")

```

```{r}
library(extrafont); font_import(pattern = "Montserrat")

plot_lad <- 
hld_lad %>%
  ggplot(aes(geometry = geometry)) +
  geom_sf(aes(fill = deaths), color = "#b4b3b4") +
  nord::scale_fill_nord(palette = "lumina", na.value = "white", discrete = FALSE) +
  #geom_sf_label(aes(x = long, y = lat, label = label),
  #              color = "grey10", size = 2.5, nudge_x = 50000, nudge_y = 50000,
  #              segment = TRUE, segment.color = "grey80", segment.size = 0.5) +
  labs(title = str_wrap("Homelessness Deaths within each UK Local Authority District", 20),
       fill  = "Homeless Deaths") +
  coord_sf() +
  theme_void() +
  theme(plot.title   = element_text(family = "Montserrat SemiBold", color = "#454545", vjust = -20, hjust = 0, size = 20),
        legend.title = element_text(family = "Montserrat SemiBold", color = "#454545", vjust = 1,   hjust = 0, size = 8),
        legend.position = c(0.19,0.83),
        legend.direction = "horizontal",
        legend.key.width  = unit(1  , units = "cm"),
        legend.key.height = unit(0.2, units = "cm"))

```

```{r}
# save
ggsave(plot = plot_lad, here::here("projects/homelessness/hld_lad.png"), bg = "white", dpi = 360, height = 10, width = 10)

```

######## LEAFLET

```{r}

lad_tf <- spTransform(CRS("+proj=longlat +datum=WGS84 +no_defs"))

hld_lad_shp <- sp::merge(lad_tf, hld_flt, by.x = "LAD21CD" , by.y = "area_code", duplicateGeoms = TRUE)

```

```{r}
library(leaflet)
# http://bboxfinder.com/#0.000000,0.000000,0.000000,0.000000

palette <- colorNumeric(nord::nord("lumina"), domain = hld_lad_shp@data$deaths, na.color = "white")

hld_lad_shp %>%
leaflet(options = leafletOptions(minZoom = 6, maxZoom = 11)) %>% 
  addProviderTiles(provider = "Esri.WorldGrayCanvas") %>%
  setView(lng = -2.1, lat = 55, zoom = 6) %>%      
  addPolygons(weight    = 1,      
              color     = ~palette(deaths),      
              fillOpacity = ~if_else(is.na(deaths), 0,1),       
              label     = ~label) 
  

```
