---
title: "UK lvl 1 Region - Population Over Time"
author: "NearAndDistant"
date: "12/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Download Region JSON from ONS Boundaries
```{r}
library(tidyverse)
library(sf)
library(jsonlite)

#load geojson from url
uk_region_boundaries_raw <- st_read('https://opendata.arcgis.com/datasets/01fd6b2d7600446d8af768005992f76a_3.geojson')

uk_regions_boundaries <- 
  uk_region_boundaries_raw %>% 
  rename(name = nuts118nm) %>% 
  mutate(name = str_remove(name , " \\(England\\)"), 
         name = str_to_title(name), 
         name = if_else(name == "East Of England" , "East" , name))

```

### Download ONS Population Time Series
```{r}

uk_pop_1991_to_2020_raw <-
read_csv("https://raw.githubusercontent.com/NearAndDistant/ruk/main/data_scripts/outputs/uk_pop_1991_to_2020.csv")

uk_pop_timeseries <- # headline uk figures cannot be replicated from bottom-up data therefore string these separate
uk_pop_1991_to_2020_raw[which(uk_pop_1991_to_2020_raw$name == "United Kingdom"),-1:-3] %>%
pivot_longer(cols = everything(), values_to = "uk_population" , names_to = "year")

uk_pop_region_1991_to_2020 <- 
  uk_pop_1991_to_2020_raw %>% 
  filter(geography == "Region" | name == "Scotland" | name == "Northern Ireland" | name == "Wales") %>%
  pivot_longer(cols = `1991`:`2020`, names_to = "year" , values_to = "population") %>%
  inner_join(uk_pop_timeseries , by = "year") %>%
  group_by(year) %>%
  mutate(pc_population = population / uk_population,
         label         = paste(year , " (" ,round(uk_population / 1000000,2) , "m)", sep = ""),
         label         = factor(label)) %>%
  ungroup()

```

##### Merging for Maps
```{r}

uk_geopop_1991_to_2020 <- 
uk_regions_boundaries %>%
  inner_join(uk_pop_region_1991_to_2020 , by = "name")

```

###### Create UK Outline
```{r}
library(rnaturalearth)

uk      <- ne_countries(scale = "medium", returnclass = "sf", country = "United Kingdom")
ireland <- ne_countries(scale = "medium", returnclass = "sf", country = "Ireland")

```

##### Mapping
```{r}

plot_uk_geomap_1991_to_2020 <- 
uk_geopop_1991_to_2020 %>%
  filter(year %in% c(1991, seq(1995,2020,5))) %>%
  ggplot() +
  geom_sf(data = ireland, fill = "white" , color = "grey80") +
  geom_sf(aes(fill = pc_population), color = "white") +
  scale_fill_viridis_c(labels = scales::percent_format(accuracy = 1) , direction = -1) +
  coord_sf() +
  facet_wrap(~label, nrow = 1, strip.position = "bottom") +
  labs(fill = "Population") +
  ggthemes::theme_map() +
  theme(plot.background = element_rect(fill = "white" , color = "white"),
        legend.position = "bottom", 
        legend.title = element_text(size = 12, face = "bold" , vjust = 0.75),
        legend.justification = c(0.5,0),
        strip.background = element_rect(fill = "white" , color = "white"),
        strip.text = element_text(size = 12 , face = "bold"))

```

##### Outputs
```{r}
library(usethis)

ggsave(here::here("projects/uk_pop_map.png"), dpi = 360, height = 10, width = 15)

```

