---
title: "private_public_unions"
author: "NearAndDistant"
date: "2022-07-27"
output: html_document
---

Table 2.1a: Trade Union Membership levels by sector and gender, 1995 to 2021

```{r}
library(tidyverse)

temp          <- read_rds(here::here("trade_union_stats_may2022.rds"))
unions_pp_raw <- readODS::read_ods(temp, sheet = "2_1A", range = c("A4:G31"), col_names = TRUE)

```

```{r}
# union membership in '000

unions_pp <- unions_pp_raw |>
  janitor::clean_names() |>
  rename("private_all" = 2, "private_male" = 3, "private_female" = 4, "public_all" = 5, "public_male" = 6, "public_female" = 7) |>
  pivot_longer(cols = c(2:7)) |>
  mutate(sector = str_extract(name, "[^_]+"),
         name   = str_remove(name, "[^_]+_")) |>
  select(year, sector, name, value)

```

```{r}

unions_pp |>
  filter(name != "all") |>
  mutate(value = if_else(name == "male", value*-1, value)) |>
  ggplot(aes(year, value, fill = name)) +
  geom_bar(stat = "identity") + 
  scale_x_reverse(breaks = c(1995:2021)) +
  facet_share(~name, dir = "h", scales = "free", reverse_num = TRUE) +
  coord_flip()

```

