---
title: "Education Level"
author: "NearAndDistant"
date: "2022-07-29"
output: html_document
---

Table A17: Age distribution of employees who are trade union members, UK, 1995 and 2021 

```{r}
library(tidyverse)

temp       <- read_rds(here::here("trade_union_stats_may2022.rds"))
unions_raw <- readODS::read_ods(temp, sheet = "A17", range = c("A4:C8"), col_names = TRUE)

# clean
union_age <- unions_raw |>
  janitor::clean_names() |>
  rename(age = "category") |>
  pivot_longer(cols = c(2:3), names_to = "year", values_to = "percent") |>
  mutate(age      = str_remove(age, "Age bands: "),
         year     = str_sub(year, start = 2, end = 5), 
         year     = as.numeric(year),
         label    = year,
         label    = factor(label),
         fill     = if_else(age != "50 plus", "grey", as.character(label)),
         fill     = if_else(age != "50 plus" & year == 2021, "grey1", fill),
         percent  = round(percent,0)/100)

```

```{r}
library(extrafont); font_import(pattern = "Montserrat")

plot_age <-
union_age |>
  ggplot(aes(percent, fct_rev(age), fill = fct_rev(fill))) +
  geom_col(position = position_dodge(width = 1), show.legend = FALSE) +
  geom_text(aes(label = label), position = position_dodge(width = 1), hjust = -0.1, family = "Montserrat") +
  scale_x_continuous(NULL, expand = c(0,0), limits = c(0,0.5), labels = scales::percent_format()) +
  scale_fill_manual(NULL, values = c("#eeeeee", "#eeeeee", "#f17279", "#74b2bd")) +
  labs(y = NULL, 
       title   = "Age Distribution of Employees who are Trade Union Members, UK (1995 & 2021)",
       caption = "Graphic: @NearAndDistant | Source: Office for National Statistics") +
  theme_minimal() +
  theme(plot.title         = element_text(size = 16, hjust = 0, vjust = 2, family = "Montserrat SemiBold"),
        plot.caption       = element_text(size = 9, color = "grey50", hjust = 1, vjust = -6, family = "Montserrat"),
        axis.text.x        = element_text(family = "Montserrat", size = 12),
        axis.text.y        = element_text(family = "Montserrat SemiBold", size = 12),
        panel.grid         = element_blank(),
        panel.grid.major.x = element_line(color = "grey90", size = 0.25),
        plot.margin        = margin(1,2,1,1, unit = "cm"))

```

```{r}

ggsave(plot = plot_age, here::here("Outputs/Trade Unions - Age Distribution.png"), width = 13, height = 10, dpi = 360, bg = "white")

```