---
title: "Education"
author: "NearAndDistant"
date: "2022-07-29"
output: html_document
---

Table 1.5: UK Trade union membership as a % of employees by education, 2021

```{r}
library(tidyverse)

temp       <- read_rds(here::here("trade_union_stats_may2022.rds"))
unions_raw <- readODS::read_ods(temp, sheet = "1_5", range = c("A18:B23"), col_names = FALSE)

# clean
union_edu <- unions_raw |>
  janitor::clean_names() |>
  rename(highest_qual = a, percent = b) |>
  mutate(highest_qual = str_remove(highest_qual, "Highest qualification: "),
         highest_qual = str_to_title(highest_qual),
         highest_qual = factor(highest_qual, 
                               levels = c("No Qualification", "Other Qualifications", "Gcse Grades A-C Or Equivalent",
                                          "A-Level Or Equivalent", "Degree Or Equivalent", "Other Higher Education"),
                               ordered = TRUE),
         highest_qual = fct_recode(highest_qual, `GCSE Grades A-C Or Equivalent` = "Gcse Grades A-C Or Equivalent"), 
         percent      = round(percent,0)/100)

```

```{r}
library(extrafont); font_import(pattern = "Montserrat")
library(MetBrewer)

scales::show_col(MetBrewer::met.brewer("Cross", 6))

plot_edu <-
union_edu |>
  ggplot(aes(highest_qual, percent, fill = highest_qual)) +
  geom_col(show.legend = FALSE) +
  geom_text(aes(label = str_wrap(highest_qual,25)), nudge_y = 0.015, hjust = 0.5, family = "Montserrat SemiBold") +
  scale_y_continuous(labels = scales::percent_format(), limits = c(0,0.5)) +
  scale_fill_met_d("Cross") +
  labs(y = NULL, 
       title   = "UK Trade Union Membership as a % of Employees by Education (2021)",
       caption = "Graphic: @NearAndDistant | Source: Office for National Statistics") +
  theme_minimal() +
  theme(plot.title         = element_text(size = 16, hjust = 0, vjust = 2, family = "Montserrat SemiBold"),
        plot.caption       = element_text(size = 9, color = "grey50", hjust = 1, vjust = 4, family = "Montserrat"),
        axis.title         = element_blank(),
        axis.text.x        = element_blank(),
        axis.text.y        = element_text(family = "Montserrat", size = 12),
        panel.grid         = element_blank(),
        panel.grid.major.y = element_line(color = "grey90", size = 0.25),
        plot.margin        = margin(1,2,0.5,1, unit = "cm"))

```

```{r}

ggsave(plot = plot_edu, here::here("Outputs/Trade Unions - Edu Distribution.png"), width = 13, height = 10, dpi = 360, bg = "white")

```
