---
title: "Mapping Gross Income"
author: "NearAndDistant"
date: "13/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### Grab Boundaries from ONS
```{r}
library(tidyverse)
library(sf)

#load geojson from url
uk_regions_boundaries <-
st_read('https://opendata.arcgis.com/datasets/01fd6b2d7600446d8af768005992f76a_3.geojson') %>%
  rename(region_name = nuts118nm) %>% 
  mutate(region_name = str_remove(region_name , " \\(England\\)"), 
         region_name = str_to_title(region_name))  %>%
  mutate(region_name = if_else(region_name == "Yorkshire And The Humber", "Yorkshire", region_name))

```

#### Grab ONS Gross Data from GitHub (Script in Repository)
```{r}

# you can see the primary script to grab this at https://raw.githubusercontent.com/NearAndDistant/ruk/main/data_scripts/ons_gross_income_1997_to_2018/
ons_gross_income_1997_to_2018 <-
read_csv("https://raw.githubusercontent.com/NearAndDistant/ruk/main/data_scripts/ons_gross_income_1997_to_2018/ons_gross_income_1997_to_2018.csv")

```

##### Grabs NUTS1
```{r}

ons_gross_income_1997_to_2018_NUTS1 <-
ons_gross_income_1997_to_2018 %>%
  filter(`NUTS level` == "NUTS1") %>%
  janitor::clean_names(numerals = "left") %>%
  pivot_longer(cols = starts_with("x") , names_to = "year" , values_to = "gross_income") %>%
  mutate(year = str_remove(year , "x"),
         year = as.numeric(year),
         region_name = str_to_title(region_name)) %>%
  mutate(region_name = if_else(region_name == "Yorkshire And The Humber", "Yorkshire", region_name)) %>%
  # rate of change summary for sec_axis_labels 
  group_by(region_name) %>%
  mutate(region_ror = (last(gross_income) - first(gross_income)) / first(gross_income)) %>%
  mutate(sec_axis_labels = paste0(region_name, " (+", scales::percent(region_ror, accuracy = 2),")")) %>%
  ungroup()

```

##### Merging for Map
```{r}

uk_gross_1997_to_2018 <- 
uk_regions_boundaries %>%
  inner_join(ons_gross_income_1997_to_2018_NUTS1 , by = "region_name")

```

###### Create UK Outline
```{r}
library(rnaturalearth)

uk      <- ne_countries(scale = "medium", returnclass = "sf", country = "United Kingdom")
ireland <- ne_countries(scale = "medium", returnclass = "sf", country = "Ireland")

```

##### Plot Regional Rate of Change 
```{r}
theme_set(theme_minimal())

text <- 'GDHI is the amount of money that all individuals in an average regional household have available after they have paid direct and indirect taxes and received any direct benefits.\nGDHI is a concept that is seen to reflect the “material welfare” of the household. Regional estimates are produced in current prices (which include the effects of inflation).'

scotland_y_coord <- 
ons_gross_income_1997_to_2018_NUTS1$gross_income[which(ons_gross_income_1997_to_2018_NUTS1$year == 2018 & ons_gross_income_1997_to_2018_NUTS1$region_name =="Scotland")]

plot_region_gdhi_roc <-
ons_gross_income_1997_to_2018_NUTS1 %>%
mutate(region_name = if_else(region_name == "Yorkshire And The Humber", "Yorkshire", region_name)) %>%
  ggplot(aes(year , gross_income , color = gross_income, group = region_name)) +
  geom_line(show.legend = TRUE , size = 1.5) +
  geom_curve(x = 2018, y = scotland_y_coord + 50000, xend = 2018, yend = scotland_y_coord, arrow = arrow(length = unit(0.03, "npc")), color = "grey30") +
  scale_x_continuous(breaks = c(1997,seq(2000,2015,5),2018), limits = c(1997,2018), expand = c(0,0)) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1 , prefix = "£"), breaks = seq(0,250000,50000),
                     sec.axis = dup_axis(breaks = ons_gross_income_1997_to_2018_NUTS1$gross_income[which(ons_gross_income_1997_to_2018_NUTS1$year == 2018)],
                                         labels = ons_gross_income_1997_to_2018_NUTS1$sec_axis_labels[which(ons_gross_income_1997_to_2018_NUTS1$year == 2018)],
                                         guide  = guide_axis(check.overlap = TRUE))) +
  scale_color_viridis_c(labels = scales::comma_format(accuracy = 1 , prefix = "£"), direction = -1) +
  coord_cartesian(clip = "off") +
  labs(title = "ONS Regional Gross Disposable Household Income (GDHI) 1997 to 2018",
       subtitle = text,
       fill = NULL,
       x = NULL,
       y = NULL) +
  theme(plot.background = element_rect(fill = "white" , color = "white"),
        plot.title = element_text(size = 24 , face = "bold" , hjust = 0, vjust = 6),
        plot.subtitle = element_text(size = 14 , hjust = 0 , vjust = 9),
        legend.position = c(0.17,1),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.key.width = unit(2.5, "cm"),
        panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(), 
        axis.title.y.right = element_blank(), 
        axis.text.y.right = element_text(size = 9),
        axis.text.x = element_blank(),
        plot.margin = margin(2,0.5,14,1, unit = "cm"))

```

##### Plot Map Regional Change
```{r}

plot_uk_gdhi_1997_2018 <-
uk_gross_1997_to_2018 %>%
  filter(year %in% c(1997,seq(2000,2015,5),2018)) %>%
  ggplot() +
  geom_sf(data = ireland, fill = "white" , color = "grey80") +
  geom_sf(aes(fill = gross_income), color = "white" , show.legend = FALSE) +
  scale_fill_viridis_c(labels = scales::comma_format(accuracy = 1 , prefix = "£") , direction = -1) +
  coord_sf() +
  facet_wrap(~year, nrow = 1, strip.position = "top") +
  ggthemes::theme_map() +
  theme(plot.background = element_rect(fill = "white" , color = "white"),
        strip.background = element_rect(fill = "white" , color = "white"),
        strip.text = element_text(size = 14 , face = "bold"),
        plot.margin = margin(-1,0,-3,0, unit = "cm"))

```

##### Panel
```{r}
library(cowplot)

ons_region_gdhi_1997_2018 <-
ggdraw(plot_region_gdhi_roc) +
  draw_plot(plot_uk_gdhi_1997_2018, height = 0.6) +
  draw_text(ons_gross_income_1997_to_2018_NUTS1$sec_axis_labels[which(ons_gross_income_1997_to_2018_NUTS1$region_name == "North West")] ,
            size = 9 , hjust = 0 , x = 0.905 , y = 0.6635, color = "grey50") +
  draw_text(ons_gross_income_1997_to_2018_NUTS1$sec_axis_labels[which(ons_gross_income_1997_to_2018_NUTS1$region_name == "Scotland")] , 
            size = 9 , hjust = 0 , x = 0.905 , y = 0.705, color = "grey50") +
  draw_text("Data: ONS | Licence: Open Government Licence | Graphic: @NearAndDistant" ,   size = 12 , hjust = 0 , x = 0.36 , y = 0.86) +
  theme(plot.background = element_rect(fill = "white" , color = "white"))

# Create Directory and Save

dir.create(here::here("projects/ons_region_gdhi_1997_2018"))

ggsave(here::here("projects/ons_region_gdhi_1997_2018/ons_region_gdhi_1997_2018.png"), dpi = 360, height = 11, width = 17 , plot = ons_region_gdhi_1997_2018)

```

## Modelling

##### Linear Model to 2030
```{r}

mdl_gdhi <- lm(gross_income ~ year * region_name + 0, data = ons_gross_income_1997_to_2018_NUTS1)

# Prediction method
explanatory_var <-
  expand_grid(year = seq(1997,2030,1),
              region_name = unique(ons_gross_income_1997_to_2018_NUTS1$region_name))

prediction_data <-
explanatory_var %>%
  mutate(gross_income = predict(mdl_gdhi , explanatory_var),
         upper_ci     = predict(mdl_gdhi , explanatory_var , interval = "confidence")[,2],
         lower_ci     = predict(mdl_gdhi , explanatory_var , interval = "confidence")[,3])

```

```{r}

prediction_data <-
prediction_data %>%
  group_by(region_name) %>%
  mutate(region_ror = (last(gross_income) - first(gross_income)) / first(gross_income)) %>%
  mutate(sec_axis_labels = paste0(region_name, " (+", scales::percent(region_ror, accuracy = 2),")")) %>%
  ungroup()

```

##### Model Visualisation
```{r}

text_mdl <- 'Each year the Office of National Statistics in the UK release GDHI figures. GDHI is the amount of money that all individuals in an average regional household have available\nafter they have paid direct and indirect taxes and received any direct benefits. Regional estimates are produced in current prices (which include the effects of inflation).\nUsing these figures we can create a linear model and project regional disposable income out to 2030.'

scotland_y_coord_mdl <- 
prediction_data$gross_income[which(prediction_data$year == 2030 & prediction_data$region_name =="Scotland")]

plot_mdl_roc <- 
prediction_data %>%
mutate(region_name = if_else(region_name == "Yorkshire And The Humber", "Yorkshire", region_name)) %>%
  ggplot(aes(year , gross_income , group = region_name)) +
  geom_line(color = "grey70" , alpha = 0.5) +
  geom_curve(x = 2030, y = scotland_y_coord_mdl + 70000, xend = 2030, yend = scotland_y_coord_mdl, arrow = arrow(length = unit(0.03, "npc")), color = "grey30") +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha = 0.1) +
  geom_line(data = ons_gross_income_1997_to_2018_NUTS1 , aes(color = gross_income), show.legend = TRUE , size = 2) +
  scale_x_continuous(breaks = c(1997,seq(2000,2030,5)), limits = c(1997,2030), expand = c(0,0)) +
  scale_y_continuous(labels = scales::comma_format(accuracy = 1 , prefix = "£"), breaks = seq(0,350000,50000),
                     sec.axis = dup_axis(breaks = prediction_data$gross_income[which(prediction_data$year == last(prediction_data$year))],
                                         labels = prediction_data$sec_axis_labels[which(prediction_data$year == last(prediction_data$year))],
                                         guide  = guide_axis(check.overlap = TRUE))) +
  scale_color_viridis_c(option = "cividis", labels = scales::comma_format(accuracy = 1 , prefix = "£"), begin = 1, end = 0.35) +
  coord_cartesian(clip = "off") +
  labs(title = "Regional Gross Disposable Household Income (GDHI) 1997-2030 - Projections",
       subtitle = text_mdl,
       x = NULL , y = NULL , color = NULL) +
  theme(plot.background = element_rect(fill = "white" , color = "white"),
        plot.title = element_text(size = 24 , face = "bold" , hjust = 0, vjust = 8),
        plot.subtitle = element_text(size = 14 , hjust = 0 , vjust = 11),
        legend.position = c(0.17,1.025),
        legend.direction = "horizontal",
        legend.title = element_blank(),
        legend.key.width = unit(2.5, "cm"),
        panel.grid.minor = element_blank(), 
        panel.grid.major.x = element_blank(), 
        axis.title.y.right = element_blank(), 
        axis.text.y.right = element_text(size = 9),
        axis.text.x = element_blank(),
        plot.margin = margin(2,0.5,13,1, unit = "cm"))
  
```

```{r}

plot_mdl_map_roc <- 
prediction_data %>%
  inner_join(uk_regions_boundaries , by = "region_name") %>%
  filter(year %in% c(1997,2000,2010,2018,2025,2030)) %>%
  ggplot() +
  geom_sf(data = ireland, fill = "white" , color = "grey80") +
  geom_sf(aes(fill = gross_income , geometry = geometry), color = "white" , show.legend = FALSE) +
  scale_fill_viridis_c(option = "cividis" , labels = scales::comma_format(accuracy = 1 , prefix = "£") , direction = -1) +
  coord_sf() +
  facet_wrap(~year, nrow = 1, strip.position = "top") +
  ggthemes::theme_map() +
  theme(plot.background = element_rect(fill = "white" , color = "white"),
        strip.background = element_rect(fill = "white" , color = "white"),
        strip.text = element_text(size = 14 , face = "bold"),
        plot.margin = margin(-2,1,-6,0, unit = "cm"))

```

##### Panel
```{r}
library(cowplot)

mdl_region_gdhi_1997_2030 <-
ggdraw(plot_mdl_roc) +
  draw_plot(plot_mdl_map_roc, height = 0.6) +
  draw_text(ons_gross_income_1997_to_2018_NUTS1$sec_axis_labels[which(ons_gross_income_1997_to_2018_NUTS1$region_name == "North West")] ,
            size = 9 , hjust = 0 , x = 0.905 , y = 0.63, color = "grey50") +
  draw_text(ons_gross_income_1997_to_2018_NUTS1$sec_axis_labels[which(ons_gross_income_1997_to_2018_NUTS1$region_name == "Scotland")] , 
            size = 9 , hjust = 0 , x = 0.905 , y = 0.68, color = "grey50") +
  draw_text("Data: ONS | Licence: Open Government Licence | Graphic: @NearAndDistant" ,   size = 12 , hjust = 0 , x = 0.36 , y = 0.85) +
  theme(plot.background = element_rect(fill = "white" , color = "white"))

# Saving
ggsave(here::here("projects/ons_region_gdhi_1997_2018/mdl_gdhi_1997_2030.png"), dpi = 360, height = 11, width = 17 , plot = mdl_region_gdhi_1997_2030)

```